/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface LPFeeLibraryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DYNAMIC_FEE_FLAG"
      | "MAX_LP_FEE"
      | "OVERRIDE_FEE_FLAG"
      | "REMOVE_OVERRIDE_MASK"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DYNAMIC_FEE_FLAG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LP_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OVERRIDE_FEE_FLAG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REMOVE_OVERRIDE_MASK",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DYNAMIC_FEE_FLAG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_LP_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "OVERRIDE_FEE_FLAG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REMOVE_OVERRIDE_MASK",
    data: BytesLike
  ): Result;
}

export interface LPFeeLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): LPFeeLibrary;
  waitForDeployment(): Promise<this>;

  interface: LPFeeLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DYNAMIC_FEE_FLAG: TypedContractMethod<[], [bigint], "view">;

  MAX_LP_FEE: TypedContractMethod<[], [bigint], "view">;

  OVERRIDE_FEE_FLAG: TypedContractMethod<[], [bigint], "view">;

  REMOVE_OVERRIDE_MASK: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DYNAMIC_FEE_FLAG"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LP_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OVERRIDE_FEE_FLAG"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REMOVE_OVERRIDE_MASK"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
