/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  BeforeSwapDeltaLibrary,
  BeforeSwapDeltaLibraryInterface,
} from "../../../../../../@uniswap/v4-core/src/types/BeforeSwapDelta.sol/BeforeSwapDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BeforeSwapDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6087610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806391cb4669146038575b600080fd5b603f600081565b60405190815260200160405180910390f3fea264697066735822122075dfce9c29f1e5164e0938424cc7e13929f310257427ac4ae1083581d2d5b12e64736f6c63430008180033";

type BeforeSwapDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BeforeSwapDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BeforeSwapDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BeforeSwapDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BeforeSwapDeltaLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BeforeSwapDeltaLibrary__factory {
    return super.connect(runner) as BeforeSwapDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BeforeSwapDeltaLibraryInterface {
    return new Interface(_abi) as BeforeSwapDeltaLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BeforeSwapDeltaLibrary {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BeforeSwapDeltaLibrary;
  }
}
