/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Hooks,
  HooksInterface,
} from "../../../../../@uniswap/v4-core/src/libraries/Hooks";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "hooks",
        type: "address",
      },
    ],
    name: "HookAddressNotValid",
    type: "error",
  },
  {
    inputs: [],
    name: "HookCallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "HookDeltaExceedsSwapAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidHookResponse",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202f90ffe118c1df0add98782b9ae70306d78f62fd0d4dc2176102b0fb22bb2be964736f6c63430008180033";

type HooksConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HooksConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Hooks__factory extends ContractFactory {
  constructor(...args: HooksConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Hooks & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Hooks__factory {
    return super.connect(runner) as Hooks__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HooksInterface {
    return new Interface(_abi) as HooksInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Hooks {
    return new Contract(address, _abi, runner) as unknown as Hooks;
  }
}
